config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:session]
  get 'quotes/import'
  get 'subscribers/index'
  get 'welcome/index'
  get 'quotes/visitor_quote'
  root to: "welcome#index"

  resources :quotes, only: [:new, :index, :create, :show]
  resources :subscribers
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord


end

app/models/search.rb
class Search
  def search
    @search = Search.all
  end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :name, :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.all
    @quotes = Quote.where("quote LIKE ?", "%#{params[:quote]}%")
  end

  def show
    @quote = Quote.find(params[:id])
  end

  def new
    @quote = Quote.new
  end

  def edit
  end

  def create
    @quote = Quote.new(quote_params)
    @quote.save
    redirect_to @quote
  end

  def update
  end

  def destroy
  end

  private
  def quote_params
    params.require(:quote).permit(:quote, :link, :author, :title)
  end
end

#   def quote
#     @quotes = Quote.all
#   end

#   def link
#     @link = Quote.all


#   def import
#     Quote.import(params[:file])
#     redirect_to root_url, notice: "Activity Data imported!"
#   end
# end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def index
    @subscriber = Subscriber.new
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      cookies[:saved_lead] = true
      redirect_to root_path, notice: "Saved Successfully!"
    else
      redirect_to rooth_path, notice: "Failed to save"
    end
  end

  def update
  end

  def destroy
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:name, :email)
  end
end

app/controllers/visitor_quote_controller.rb
class VisitorQuoteController < ApplicationController
  def index
    @quotes = Quote.all
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def index
    @subscriber = Subscriber.new
    @quotes = Quote.all
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      cookies[:saved_lead] = true
      redirect_to root_path, notice: "Saved Successfully!"
    else
      redirect_to rooth_path, notice: "Failed to save"
    end
  end

  def update
  end

  def destroy
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/visitor_quote_helper.rb
module VisitorQuoteHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Quotley</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//code.jquery.com/jquery-1.11.1.min.js">
    </script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

  </head>

  <body>
    <%= render "partials/navbar" %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>


    <%= yield %>

  </body>
</html>

app/views/partials/_navbar.html.erb
<div class="navbar">
  <!-- Logo -->
  <a href="/" class="navbar-brand">
    <%= image_tag "living-room-books-group.png", alt: "logo" %>
  </a>

<%= form_tag quotes_path, method: :get do %>
  <%= text_field_tag :quote,
    params[:quote],
    class: "form-control",
    placeholder: "Search"
  %>
<% end %>

<%= link_to("Add your own quote", new_quote_path, class: "btn") %>
<a href="#" class="btn"></a>

</div>

app/views/quotes/_quote.html.erb
<div class="item blog">
  <%= link_to(quote.link, class: "quote-link", target: "_blank") do %>
    <div class="content quote-box quote-box<%= [1, 2, 3].sample %>">
      <p class="quotation-mark">“</p>
      <p class="quote-text">
        <%= quote.quote %>
      </p>
      <hr>
      <div class="blog-post-actions">
        <p class="blog-post-author pull-right">
        <%= quote.author %> <br> ~ <%= quote.title %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/quotes/index.html.erb
<h1>Quotes#index</h1>
<p>Find me in app/views/quotes/index.html.erb</p>


<% @quotes.each do |quote| %>
  <%= quote.id %>
  <%= quote.quote %>
  <%= quote.link %>
  <%= quote.author %>
  <%= quote.title %>
<% end %>

<!-- in views use @quotes instead of Quote - instance variable vs class -->

app/views/quotes/new.html.erb
<div>
  <%= form_for @quote do |f| %>
    Quote: <%= f.text_field :quote %> <br>
    <% if user_signed_in? %>
      Link : <%= f.text_field :link %><br>
    <% end %>

    Author: <%= f.text_field :author %><br>
    Title : <%= f.text_area :title %><br>
  <%= f.submit %>
  <% end %>
</div>

app/views/quotes/show.html.erb
<%= Quote.all %>
<br>
<%= @quote.id %>

<br>



<!-- bad practice to use capital letter Quote in your views -->

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 50%), url('/coverphoto.jpg');">
    <div class="banner-content">
      <h1>Quotley</h1>
      <h2>Kindle readers' favourite quotes in one place</h2>
      <div>
      <br>
        <p><i>Click the quote you like and buy the book</i></p>
      </div>
    </div>
  </div>

<!-- ".item.blog .content" -->
<div class="container">
  <div class="quote-list">
    <div class="grid">
      <%= render @quotes %>
    </div>
  </div>

  <div class="subscription-form">
    <div>
      <% if cookies[:saved_subscriber] %>
        Thanks for signing up!
      <% else %>
        <h1>Sign up for the weekly newsletter</h1>
        <%= form_for @subscriber do |f| %>
          <%= f.text_field :name, placeholder: "Name" %>
          <%= f.email_field :email, placeholder: "Email" %>
          <%= f.submit %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="footer">
  <div>
    Kindle® is a registered trademark of Amazon.com Inc. Quotley is part of Amazon's Affiliate Program.
  </div>
  <br>
  <div>Icon made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/"          title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/"          title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
  <br>
  <div class="footer-copyright">
    © Quotley <%= Date.today.year %>
  </div>
  </div>



<script>
function resizeGridItem(item){
  grid = document.getElementsByClassName("grid")[0];
  rowHeight = parseInt(window.getComputedStyle(grid).getPropertyValue('grid-auto-rows'));
  rowGap = parseInt(window.getComputedStyle(grid).getPropertyValue('grid-row-gap'));
  rowSpan = Math.ceil((item.querySelector('.content').getBoundingClientRect().height+rowGap)/(rowHeight+rowGap));
    item.style.gridRowEnd = "span "+rowSpan;
}

function resizeAllGridItems(){
  allItems = document.getElementsByClassName("item");
  for(x=0;x<allItems.length;x++){
    resizeGridItem(allItems[x]);
  }
}

function resizeInstance(instance){
  item = instance.elements[0];
  resizeGridItem(item);
}

window.onload = resizeAllGridItems();
window.addEventListener("resize", resizeAllGridItems);

allItems = document.getElementsByClassName("item");
for(x=0;x<allItems.length;x++){
  imagesLoaded( allItems[x], resizeInstance);
}

</script>

</body>

</html>